# permissions for end users to view locks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lock-viewer-role
rules:
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - locks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - locks/status
  verbs:
  - get
